export const GETTAXPAYERINFOFORD01='GETTAXPAYERINFOFORD01';
export const SETTAXPAYERINFOFORD01='SETTAXPAYERINFOFORD01';
export const SETTAXPAYERINFOFORD01NON='SETTAXPAYERINFOFORD01NON';
export const SETTAXPAYERINFOFORD01REGISTER='SETTAXPAYERINFOFORD01REGISTER';
export const GETTAXPAYERINFOFORD01REGISTER='GETTAXPAYERINFOFORD01REGISTER';
export const GETERROR="GETERROR";
export const SETERROR="SETERROR";