export const MAKEPAYMNET_UPDATE ="MAKEPAYMNET_UPDATE"
export const RESET_WITHHOLDERLOGIN="RESET_WITHHOLDERLOGIN"
export const GET_SUB_DATA="GET_SUB_DATA"
export const GETMAKEPAYMENT="GETMAKEPAYMENT"
export const SETMAKEPAYMENT="SETMAKEPAYMENT"


